/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/Modal/Speedomeeter.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useStore } from "../../store/store";

const Speedomeeter = (props) => {
  const { nodes, materials } = useGLTF('./Modal/Speedomeeter.gltf')

  let openExplode = useStore((r) => r.openExplode);
  return (
    <group {...props} dispose={null}>
       {openExplode && (
      <group position={[2, 1, -1.5]} rotation={[Math.PI / 2, 0, 0]} scale={10.52}>
        <mesh geometry={nodes.Curve006.geometry} material={materials.Material} position={[0, 0, -0.02]} />
        <mesh geometry={nodes.Curve021.geometry} material={materials.SVGMat} position={[0.07, 0, 0.04]} />
        <mesh geometry={nodes.Curve045.geometry} material={materials['Material.001']} position={[0, 0, -0.03]} />
        <mesh geometry={nodes.Curve051.geometry} material={materials['Material.005']} position={[0, 0, -0.02]} />
        <mesh geometry={nodes.Curve075.geometry} material={materials['Material.003']} position={[0, 0, -0.02]} />
        <mesh geometry={nodes.Curve104.geometry} material={materials['Material.001']} position={[0, 0.01, 0]} />
        <mesh geometry={nodes.Curve117.geometry} material={materials['Material.004']} position={[0, 0, -0.01]} />
      </group>
       )}
    </group>
  )
}

useGLTF.preload('./Modal/Speedomeeter.gltf')

export default Speedomeeter;